const pLanguages = [
  "TypeScript (ts)",
  "JavaScript (js)",
  "Typescript React (tsx)",
  "JavaScript React (jsx)",
  "Rust (rs)",
  "Python (py)",
  "C (c)",
  "C++ (cpp)",
  "C# (cs)",
  "Java (java)",
  "Swift (swift)",
  "Kotlin (kt)",
  "PHP (php)",
  "Ruby (rb)",
  "Scala (scala)",
  "Go (go)",
  "Elm (elm)",
  "Elixir (ex)",
  "Erlang (erl)",
  "Haskell (hs)",
  "OCaml (ml)",
  "Julia (jl)",
  "Julia (jl)",
  "Lua (lua)",
  "R (r)",
].sort();

export default pLanguages;
